zookeeper:
        image: 'jplock/zookeeper:3.4.6'
        ports:
          - '2181:2181'
kafka:
        image: 'ches/kafka:0.10.0.1'
        links:
          - zookeeper:zookeeper
        ports:
          - "9092:9092"
elasticsearch:
        image: 'elasticsearch:2.4.1'
        ports:
          - "9200:9200"
          - "9300:9300"
        
