zookeeper:
        image: 'jplock/zookeeper:3.4.6'
        ports:
          - '2181:2181'
kafka:
        image: 'ches/kafka:0.10.0.1'
        links:
          - zookeeper:zookeeper
        ports:
          - "9092:9092"
influxdb:
        image: 'tutum/influxdb:0.13'
        environment: 
          - ADMIN_USER="root"
          - INFLUXDB_INIT_PWD="somepassword"
          - PRE_CREATE_DB="metrics"
        ports:
          - "8086:8086"
          - "8083:8083"
elasticsearch:
        image: 'elasticsearch:5.0.0'
        ports:
          - "9200:9200"
          - "9300:9300"
        
